export {
  CARD_BASE_HEIGHT,
  CARD_BASE_WIDTH,
  DETAIL_HEIGHT_RATIO,
  DETAIL_WIDTH_RATIO,
  MAGIC_HEIGHT_RATIO,
  MAGIC_WIDTH_RATIO,
  cardFitsViewport,
  computeScaledCardSize,
  getReactionDetailCardBounds,
  getReactionMagicCardBounds,
  getVotingCardBounds,
  getReactionViewUi,
  hasOwnReactionMonster,
  hasOwnReactionTrap,
} from "./reactionLayoutCore";
