export {
  TRAP_CHOICE_SECONDS,
  TRAP_CHOICE_TIMEOUT_CHOICE,
  isTrapCard,
  hasActiveTrap,
  shouldStartTrapChoice,
  buildPendingTrapChoice,
  isTrapChoiceForPlayer,
  canResolveTrapChoice,
  applyTrapChoiceUpdate,
  applyTrapDrawNoChoice,
  getTrapChoiceSecondsLeft,
  shouldAutoResolveTrapChoice,
  getTrapChoiceCardBounds,
  usesStackedTrapLayout,
} from "./trapChoiceCore";
