/** Spielereignisse für den lokalen Kommentator (MVP). */
export const COMMENTATOR_EVENTS = {
  GAME_STARTED: "GAME_STARTED",
  ROUND_STARTED: "ROUND_STARTED",
  CARD_DRAWN: "CARD_DRAWN",
  MONSTER_DRAWN: "MONSTER_DRAWN",
  MAGIC_DRAWN: "MAGIC_DRAWN",
  TRAP_DRAWN: "TRAP_DRAWN",
  EFFECT_SELECTED: "EFFECT_SELECTED",
  VOTE_STARTED: "VOTE_STARTED",
  VOTE_ACCEPTED: "VOTE_ACCEPTED",
  VOTE_REJECTED: "VOTE_REJECTED",
  PLAYER_PUNISHED: "PLAYER_PUNISHED",
  TRAP_REPLACED: "TRAP_REPLACED",
  MONSTER_EFFECT_DISABLED: "MONSTER_EFFECT_DISABLED",
  MONSTER_EFFECT_ENABLED: "MONSTER_EFFECT_ENABLED",
  MAGIC_PLAYED: "MAGIC_PLAYED",
  GAME_ENDED: "GAME_ENDED",
};
